name: Custom Action Demo
on:
  push:
    branches:
      - main

jobs:
    greet-job:
      runs-on: ubuntu-latest
      steps:
        - name: calling custome action yml
          id: greet_action
          uses: 1322harshd/greeting-action@v1.0
          with: 
            username: harsh
        
        - name: Using Action output
          run: echo "Action says- ${{ steps.greet_action.outputs.message }}"
